import type { Metadata } from "next";
import { ThemeProvider } from '../context/ThemeContext';
import localFont from "next/font/local";
import "./globals.css";

const suisse = localFont({
  src: "./fonts/SuisseIntl-Regular.ttf",
  variable: "--font-suiss-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${suisse.variable} ${suisse.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
